(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "COMBINE_TWO_STRS_SRV"
   "<COMBINE_TWO_STRS_SRV-REQUEST>"
   "COMBINE_TWO_STRS_SRV-REQUEST"
   "<COMBINE_TWO_STRS_SRV-RESPONSE>"
   "COMBINE_TWO_STRS_SRV-RESPONSE"
   "MY_SRV"
   "<MY_SRV-REQUEST>"
   "MY_SRV-REQUEST"
   "<MY_SRV-RESPONSE>"
   "MY_SRV-RESPONSE"
  ))

