// Generated by gencpp from file beginner_tutorials/combine_two_strs_srvResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_COMBINE_TWO_STRS_SRVRESPONSE_H
#define BEGINNER_TUTORIALS_MESSAGE_COMBINE_TWO_STRS_SRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct combine_two_strs_srvResponse_
{
  typedef combine_two_strs_srvResponse_<ContainerAllocator> Type;

  combine_two_strs_srvResponse_()
    : str_combine()  {
    }
  combine_two_strs_srvResponse_(const ContainerAllocator& _alloc)
    : str_combine(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _str_combine_type;
  _str_combine_type str_combine;





  typedef boost::shared_ptr< ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct combine_two_strs_srvResponse_

typedef ::beginner_tutorials::combine_two_strs_srvResponse_<std::allocator<void> > combine_two_strs_srvResponse;

typedef boost::shared_ptr< ::beginner_tutorials::combine_two_strs_srvResponse > combine_two_strs_srvResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials::combine_two_strs_srvResponse const> combine_two_strs_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.str_combine == rhs.str_combine;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2219dba361ad7f8fd59e70d5e05d8235";
  }

  static const char* value(const ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2219dba361ad7f8fULL;
  static const uint64_t static_value2 = 0xd59e70d5e05d8235ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/combine_two_strs_srvResponse";
  }

  static const char* value(const ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string str_combine\n"
;
  }

  static const char* value(const ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.str_combine);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct combine_two_strs_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::combine_two_strs_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "str_combine: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.str_combine);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_COMBINE_TWO_STRS_SRVRESPONSE_H
