// Generated by gencpp from file beginner_tutorials/combine_two_strs_srvRequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_COMBINE_TWO_STRS_SRVREQUEST_H
#define BEGINNER_TUTORIALS_MESSAGE_COMBINE_TWO_STRS_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct combine_two_strs_srvRequest_
{
  typedef combine_two_strs_srvRequest_<ContainerAllocator> Type;

  combine_two_strs_srvRequest_()
    : str1()
    , str2()  {
    }
  combine_two_strs_srvRequest_(const ContainerAllocator& _alloc)
    : str1(_alloc)
    , str2(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _str1_type;
  _str1_type str1;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _str2_type;
  _str2_type str2;





  typedef boost::shared_ptr< ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct combine_two_strs_srvRequest_

typedef ::beginner_tutorials::combine_two_strs_srvRequest_<std::allocator<void> > combine_two_strs_srvRequest;

typedef boost::shared_ptr< ::beginner_tutorials::combine_two_strs_srvRequest > combine_two_strs_srvRequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::combine_two_strs_srvRequest const> combine_two_strs_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.str1 == rhs.str1 &&
    lhs.str2 == rhs.str2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34df8d240c5fbb34c73f630b5f4c576b";
  }

  static const char* value(const ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34df8d240c5fbb34ULL;
  static const uint64_t static_value2 = 0xc73f630b5f4c576bULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/combine_two_strs_srvRequest";
  }

  static const char* value(const ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string str1\n"
"string str2\n"
;
  }

  static const char* value(const ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.str1);
      stream.next(m.str2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct combine_two_strs_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::combine_two_strs_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "str1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.str1);
    s << indent << "str2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.str2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_COMBINE_TWO_STRS_SRVREQUEST_H
